#
#Mon Mar 30 16:50:48 COT 2026
goog\:chromeOptions={args\=[--start-maximized, --disable-gpu, remote-allow-origins\=*], extensions\=[], prefs\={download.directory_upgrade\=true, download.prompt_for_download\=false, plugins.always_open_pdf_externally\=true}}
acceptInsecureCerts=false
browserName=chrome
